"""Pydantic models for ARES Structured Outputs."""

from __future__ import annotations

from pydantic import BaseModel, Field


class ResearchTask(BaseModel):
    """A single research sub-task within a plan."""
    title: str = Field(description="Short title for this research task")
    query: str = Field(description="The specific search query to execute")
    goal: str = Field(description="What this task aims to discover or verify")


class ResearchPlan(BaseModel):
    """Structured research plan generated by the Lead Architect."""
    original_query: str = Field(description="The user's original research query")
    summary: str = Field(description="High-level summary of the research strategy")
    tasks: list[ResearchTask] = Field(
        description="Ordered list of research sub-tasks to execute"
    )


class ResearchFinding(BaseModel):
    """A single fact or insight extracted by the Web Specialist."""
    task_title: str = Field(description="Which research task produced this finding")
    content: str = Field(description="The extracted fact or insight")
    source_url: str = Field(default="", description="URL where this was found")
    relevance: str = Field(description="Why this finding matters to the query")
    source_quality: int = Field(
        default=5, ge=1, le=10, description="1-10 reliability score"
    )
    is_verified: bool = Field(
        default=False, description="Whether the fact was cross-referenced"
    )


class ReportSection(BaseModel):
    """A discrete chapter of the deep research report."""
    heading: str = Field(description="The title of this section (e.g., 'Market Analysis')")
    content: str = Field(description="The detailed findings in Markdown format")


class ResearchReport(BaseModel):
    """Final synthesized report produced by the Narrative Editor."""
    title: str = Field(description="Main title of the research paper")
    subject_line: str = Field(description="Punchy, professional email subject line")
    executive_summary: str = Field(
        description="A high-level briefing, strictly under 200 words. Markdown format."
    )
    sections: list[ReportSection] = Field(
        description="The core body of the report, broken into logical sections."
    )
    sources: list[str] = Field(
        default_factory=list,
        description="All URLs cited during the research process.",
    )
