"""Resend email tool for the ARES Notification Agent."""

from __future__ import annotations

import os

from agents import function_tool
import resend


def _get_api_key() -> str:
    api_key = os.getenv("RESEND_API_KEY")
    if not api_key:
        raise RuntimeError("RESEND_API_KEY environment variable is not set")
    return api_key


def _wrap_in_template(subject: str, body: str) -> str:
    """Wrap email body content in a styled HTML template."""
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"></head>
<body style="margin:0; padding:0; background-color:#f4f4f7; font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f7;">
    <tr>
      <td align="center" style="padding:30px 10px;">
        <table role="presentation" width="640" cellpadding="0" cellspacing="0"
               style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.08); overflow:hidden;">

          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 50%,#0f3460 100%); padding:32px 40px;">
              <h1 style="margin:0; color:#ffffff; font-size:22px; font-weight:700; letter-spacing:0.5px;">
                ARES Research System
              </h1>
              <p style="margin:6px 0 0; color:#a0aec0; font-size:13px;">
                Autonomous Research &amp; Extraction System
              </p>
            </td>
          </tr>

          <!-- Subject banner -->
          <tr>
            <td style="background-color:#e8f4fd; padding:16px 40px; border-bottom:1px solid #d0e8f5;">
              <p style="margin:0; color:#1a5276; font-size:15px; font-weight:600;">
                {subject}
              </p>
            </td>
          </tr>

          <!-- Body content -->
          <tr>
            <td style="padding:32px 40px; color:#2d3748; font-size:15px; line-height:1.7;">
              {body}
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background-color:#f8fafc; padding:24px 40px; border-top:1px solid #e2e8f0;">
              <p style="margin:0; color:#a0aec0; font-size:12px; text-align:center;">
                Generated by ARES — Autonomous Research &amp; Extraction System<br>
                Powered by OpenAI Agents SDK &amp; Tavily Search
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>"""


@function_tool
def send_email(to: str, subject: str, body: str) -> str:
    """Send an email with the research report via Resend.

    Args:
        to: Recipient email address.
        subject: Email subject line.
        body: Email body content in HTML format. Use proper HTML tags:
              <h2> for section headings, <p> for paragraphs,
              <ul><li> for lists, <strong> for bold, <a> for links.
    """
    resend.api_key = _get_api_key()

    html = _wrap_in_template(subject, body)

    response = resend.Emails.send(
        {
            "from": "ARES Research <onboarding@resend.dev>",
            "to": [to],
            "subject": subject,
            "html": html,
        }
    )

    email_id = response.get("id", "unknown")
    return f"Email sent successfully. ID: {email_id}"
