find_trending_schools_teachers:
  description: >
    Find the top trending schools and teachers across the world in {sector} by searching the various Global school Databases. Find new schools and teachers that you've not found before. Metrics can be unique initiatives, awards, achievements, etc.
  expected_output: >
    A list of trending schools and teachers in {sector}
  agent: trending_schools_teachers_finder
  output_file: output/trending_schools_teachers.json

research_trending_schools_teachers:
  description: >
    Given a list of trending , provide detailed analysis of each school and teacher in a report by searching online
  expected_output: >
    A report containing detailed analysis of each school and teacher
  agent: global_educational_researcher
  context:
    - find_trending_schools_teachers
  output_file: output/research_report.json

pick_best_school_teacher:
  description: >
    Analyze the research findings and pick the best school and teacher for the user.
    Send a push notification to the user with the decision and 1 sentence rationale.
    Then respond with a detailed report on why you chose this school and teacher, and which schools and teachers were not selected.
  expected_output: >
    The chosen school and teacher and why it was chosen; the schools and teachers that were not selected and why they were not selected.
  agent: best_school_teacher_picker
  context:
    - research_trending_schools_teachers
  output_file: output/decision.md

