import os
from dotenv import load_dotenv
from agents import Agent, Runner
from agents.mcp import MCPServerStdio

# Securely load environment variables
dotenv_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..', '.env'))
load_dotenv(dotenv_path, override=True)

# Important logic to trick OpenAI SDK to hit OpenRouter
if os.getenv("OPENROUTER_API_KEY"):
    os.environ["OPENAI_API_KEY"] = os.getenv("OPENROUTER_API_KEY")
    os.environ["OPENAI_BASE_URL"] = "https://openrouter.ai/api/v1"
    # Suppress AGENT tracing if OpenRouter is being used to prevent 401 warnings
    if "AGENTS_TRACING_ENABLED" not in os.environ:
        os.environ["AGENTS_TRACING_ENABLED"] = "false"

def get_system_instructions() -> str:
    """Returns the core personality and instructions for the agent."""
    return """
    You are the City Matchmaker, a knowledgeable real estate and lifestyle AI assistant.
    You take user criteria (like budget and city preferences) and use your available tools 
    to find cost of living, available apartments, and neighborhood vibes.
    Present your findings clearly using Markdown with nice bullet points. Provide a final 
    recommendation on which city fits best based on all the simulated data you find.
    """

async def run_agent_query(user_request: str) -> str:
    """
    Spawns the MCP Server and executes the AI logic via the Agents SDK.
    
    Args:
        user_request: The user's chat prompt.
        
    Returns:
        The text response generated by the AI agent.
    """
    # Set up our MCP Server Subprocess Configuration
    matchmaker_params = {"command": "uv", "args": ["run", "matchmaker_server.py"]}
    
    # Context manager to initialize and cleanup the MCP server connection securely 
    async with MCPServerStdio(params=matchmaker_params, client_session_timeout_seconds=60) as server:
        
        agent = Agent(
            name="matchmaker_agent",
            instructions=get_system_instructions(),
            model="openai/gpt-4o-mini",
            mcp_servers=[server]
        )
        
        # Dispatch the Runner and wait for tools to resolve
        result = await Runner.run(agent, user_request)
        return result.final_output
